-------------------------------------------------------------------------------
Test set: com.river.utils.MathUtilsTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.095 s <<< FAILURE! - in com.river.utils.MathUtilsTest
testDivide  Time elapsed: 0.023 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Divide by zero should throw ==> Unexpected exception type thrown ==> expected: <java.lang.NullPointerException> but was: <java.lang.ArithmeticException>
	at com.river.utils.MathUtilsTest.testDivide(MathUtilsTest.java:20)
Caused by: java.lang.ArithmeticException: / by zero
	at com.river.utils.MathUtilsTest.lambda$testDivide$0(MathUtilsTest.java:20)
	at com.river.utils.MathUtilsTest.testDivide(MathUtilsTest.java:20)

